export const categorySubcategories = {
  Football: [
    'Ghana Football',
    'Ghana Premier League',
    'Division One League',
    'MTN FA Cup',
    'Women’s Football',
    'Black Stars',
    'Black Queens',
    'Black Starlets',
    'Black Satellites',
    'Black Meteors',
    'Black Princesses',
    'Black Maidens',
    'Ghana Futsal National Team',
    'Ghana Beach Soccer National Team',
    'Ghana Amputee National Team',
    'Ghana Deaf National Football Team',
    'Ghanaians Abroad',
    'Premier League',
    'English Championship',
    'European Football',
    'LaLiga',
    'Bundesliga',
    'Serie A',
    'Ligue 1',
    'English Football',
    'Italian Football',
    'Spanish Football',
    'German Football',
    'French Football',
    'UEFA Champions League',
    'UEFA Europa League',
    'UEFA Conference League',
    'African Football',
    'CAF Champions League',
    'CAF Confederation Cup',
    'AFCON',
    "Women's AFCON",
    'World Football',
    'FIFA World Cup',
    'FIFA Club World Cup',
    'International Friendlies',
    'Transfer News & Rumours'
],

  Basketball: [
    'NBA',
    'WNBA',
    'EuroLeague',
    'Accra Basketball League',
    'FIBA Competitions',
    'African Basketball League',
    'Local Basketball',
    'School & University Basketball',
    'African Basketball',
    'Other Basketball',
  ],

  Athletics: [
    'Track Events',
    'Field Events',
    'Road Races & Marathons',
    'Commonwealth Games',
    'World Athletics Championships',
    'African Athletics',
    'Local Athletics',
    'School & University Athletics',
    'Olympic Athletics',
    'Other Athletics Events',
  ],

  Boxing: [
    'Local Boxing',
    'International Boxing',
    'Olympic Boxing',
  ],

  Motorsport: [
    'Formula 1',
    'Formula E',
    'MotoGP',
    'Rally',
    'NASCAR',
    'Racing'
  ],

  Tennis: [
    'ATP Tour',
    'WTA Tour',
    'Australian Open',
    'Roland Garros',
    'Wimbledon',
    'US Open',
    'Local Tennis',
    'African Tennis',
    'Grand Slams',
    'Davis Cup',
    'Billie Jean King Cup',
    'Olympic Tennis',
    'Other',
  ],

  OtherSports: [
    'Esports',
    'Volleyball',
    'Handball',
    'Cricket',
    'Rugby',
    'Swimming',
    'Table Tennis',
    'Badminton',
    'Golf',
    'Netball',
    'Hockey',
    'Cycling',
    'Wrestling',
    'Arm wrestling',
    'Judo',
    'American sports',
    'Mixed Martial Arts',
    'Gymnastics',
    'Weightlifting',
    'Sailing',
    'Triathlon',
    'Olympic sports',
    'Darts',
  ],
};
